name: SonarCloud Analysis
#
on:
  push:
    branches:
      - main
      - sonarQ
      - 2-corregir-los-errores-de-mantenibilidad
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Instalar dependencias Backend
        working-directory: backend
        run: npm install

      - name: Instalar dependencias Frontend
        working-directory: frontend
        run: npm install

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.projectKey=DweskZ_Dashboard_Ambiental
            -Dsonar.organization=dweskz
            -Dsonar.sources=backend/src,frontend/src
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
